# Generated by Django 5.1.2 on 2024-11-11 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ail_park', models.CharField(choices=[('Est', 'Est'), ('Ouest', 'Ouest'), ('Nord', 'Nord'), ('Sud', 'Sud')], default='Est', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
                ('moyenne_spaces', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AverageDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_distance', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('parking_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_distance', to='station.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='station.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Manager', 'Manager')], default='Client', max_length=20)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.parkinglot')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.parkingspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasonicSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasonic_data', to='station.parkinglot')),
            ],
        ),
    ]
