# Generated by Django 5.1.2 on 2024-11-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='capacity',
            new_name='total_spaces',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='ail_park',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='moyenne_spaces',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='parking_lot',
        ),
    ]
