# Generated by Django 5.1.2 on 2024-11-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_rename_capacity_parkinglot_total_spaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='moyenne_spaces',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='available_spaces',
            field=models.IntegerField(default=0),
        ),
    ]
