# Generated by Django 5.1.2 on 2024-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_parkinglot_numero_park'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='numero_park',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='ail_park',
            field=models.CharField(choices=[('Est', 'Est'), ('Ouest', 'Ouest'), ('Nord', 'Nord'), ('Sud', 'Sud')], default='Est', max_length=50),
        ),
    ]
