# Generated by Django 5.1.2 on 2024-10-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_remove_parkinglot_numero_park_parkinglot_ail_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='parking_lot',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='station.parkinglot'),
            preserve_default=False,
        ),
    ]
