# Generated by Django 5.1.2 on 2024-10-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_reservation_parking_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='moyenne_spaces',
            field=models.FloatField(default=0.0),
        ),
    ]
