# Generated by Django 5.1.2 on 2024-10-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0008_parkinglot_moyenne_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasonicSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasonic_data', to='station.parkinglot')),
            ],
        ),
    ]
