# Generated by Django 5.1.2 on 2024-10-25 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0009_ultrasonicsensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_distance', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('parking_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_distance', to='station.parkinglot')),
            ],
        ),
    ]
