# Generated by Django 5.1.2 on 2024-10-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0010_averagedistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Manager', 'Manager')], default='Client', max_length=20),
        ),
    ]
